### ISSUE TITLE
Can't build the initial preview website.

### ISSUE THREAD

**Issue by GandhiParth** [hugo-apero/hugo-apero#104]
I am following the steps [here](https://hugo-apero-docs.netlify.app/start/create-site/?panelset=screenshot-%25F0%259F%2593%25B7&panelset2=screenshot-%25F0%259F%2593%25B73&panelset3=to-do-%25E2%259C%2594%25EF%25B8%258F4).But after running the new_site function and clicking yes to preview site. It is not building up. Kindly help out if possible. I am posting the error message below.
![Screenshot from 2023-05-30 19-24-10](https://github.com/hugo-apero/hugo-apero/assets/87466488/b86f913d-c489-47bb-b846-e13a19d42b88)

**Comment by quinix45** [comment]
Hi, 

I was experiencing the exact same issue, and after trying multiple things, what fixed it for me was downgrading to the previous hugo version (0.112.7):

`blogdown::install_hugo("0.112.7")`

After that, `serve_site()` worked! Hopefully this helps.

**Comment by quinix45** [comment]
Hi, 

I was experiencing the same issue too and I think I figured out the "problem" . This is based on my extrmely basic understanding of how `.toml` files and hugo works, but here I go:

Essentially, the variable `.textFonFamily` (as well as a couple of other variables that are called in the `scaffold.scss` file) is defined in the `config.toml` file. However, for some reason, the default `.toml` file that the hugo compiler looks at to render the website is **`hugo.toml`**, not `config.toml`. All you need to do is copy and paste all of the contents of the `config.toml` into **`hugo.toml`**. 

Also, after doing that, the only other issue that I experience was a `.md` file that would not compile:

<img width="441" alt="image" src="https://github.com/hugo-apero/hugo-apero/assets/87843002/62b23984-4812-4643-b4c9-9c6852f464c1">

Either delete the `03-distill\index.md` file ( you probably will not keep this file once you make your own website) or delete the specific line that causes the issue.

After that, the website should compile properly. 

I think this may be an issue caused by some recent updates, where the target `.toml` file is no longer the appropriate one, but I cannot say for sure. Anyone who knows more than me about the topic is welcome to correct me.

Anyway, I hope this helps anyone experiencing this issue.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
